{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baseapp.fullname" . }}
  labels:
    {{- include "baseapp.labels" . | nindent 4 }}
data:
    {{- toYaml .Values.configmap.data | nindent 4 }}
{{- end }}