{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-sample.secretName" . }}
  labels:
    {{- include "chart-sample.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data: 
  {{- with .Values.secret.data }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
