{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
type: {{ default "Opaque" .type }}
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ template "managed-secrets.name" $ }}
    chart: {{ template "managed-secrets.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{ with .labels -}}{{- toYaml . | indent 4 -}}{{- end }}
stringData:
{{ toYaml .stringData | indent 2 -}}
{{- end -}}
