{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kotlin-base-grpc.configMapName" . }}
  labels:
    {{- include "kotlin-base-grpc.labels" . | nindent 4 }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.configMap.data }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
