{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kotlin-base-grpc.secretName" . }}
  labels:
    {{- include "kotlin-base-grpc.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data: 
  {{- with .Values.secret.data }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
