apiVersion: v1
kind: Service
metadata:
  name: {{ include "kotlin-base.fullname" . }}
  labels:
    {{- include "kotlin-base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.serviceGrpc.port }}
      targetPort: {{ .Values.serviceGrpc.targetPort }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "kotlin-base.selectorLabels" . | nindent 4 }}
