apiVersion: jetstream.nats.io/v1beta1
kind: Stream
metadata:
  name: {{ include "kotlin-base.fullname" . }}
spec:
  name: {{ include "kotlin-base.fullname" . }}
  subjects: ["orders.*"]
  storage: memory
  maxAge: 1h
  replicas: 1